### PR TITLE
add download links to model page

### PR DESCRIPTION
**Pull request by nconrad**

### CODE REVIEW

**Comment by nconrad** [comment]
So, it's hard to see, but `getDownloadUrls` is the method I added to WorkspaceManager.  I did this because I like when download links are hrefs.  This avoids popups and allows "save as".  If there is a better way, let me know.  I can change it.

**Comment by dmachi** [comment]
Thats fine.  There is a download function at https://github.com/dmachi/p3-web/blob/master/public/js/p3/WorkspaceManager.js#L357-L362  that I've been meaning to change to not open in a new window.  It opens in a popup now because when downloading was first added it had some errors and I didn't want to leave users at a 500 page.  Now that it is reliable, changing that to open in the same window will avoid the popup without having to make round trips to the server to get all those download urls that might never be used ahead of time.

Dustin

**Comment by nconrad** [comment]
Yeah, that's what I figured.  What about the "save as" behavior?  Will that work the same?  It is nice to be able to rename the file or use wget.  I've wondered if there is any impact on the server by fetching the links.

**Comment by nconrad** [comment]
Btw, in the MS site I'm only fetching them if the the user hits a download button that brings up a prompt with all the links.

**Comment by dmachi** [comment]
I doubt there is much impact on the server.  The download urls do have a pretty short lifetime though.  I'm fine with the way you are doing it for now and if it all works fine and doesn't have any perf issues, I can switch the other viewers over to use that approach. Save as probably doesn't work.

**Pull request merged**
